repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args: [--in-place, --expand-star-imports, --remove-all-unused-imports]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--filter-files"]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/Pierre-Sassoulas/black-disable-checker
    rev: v1.1.1
    hooks:
    -   id: black-disable-checker
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [Flake8-pyproject, flake8-typing-imports==1.14.0, mccabe==0.7.0]
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.6'
    hooks:
    -   id: vulture
