repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
    -   id: autoflake
        args: [--in-place, --expand-star-imports, --remove-all-unused-imports]
-   repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
    -   id: isort
        args: ["--filter-files"]
-   repo: https://github.com/psf/black
    rev: 26.3.0
    hooks:
    -   id: black
-   repo: https://github.com/Pierre-Sassoulas/black-disable-checker
    rev: v1.1.3
    hooks:
    -   id: black-disable-checker
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        language: python
        additional_dependencies:
        -   flake8-pyproject==1.2.3,
        -   mccabe==0.7.0
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        language: python
        additional_dependencies:
        -   types-requests
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.15
    hooks:
    -   id: vulture
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
    -   id: codespell
        language: python
        additional_dependencies:
        -   tomli
