[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 88

[tool.vulture]
ignore_decorators = ["@discord.slash_command", "@commands.Cog.listener"]
ignore_names = ["setup"]
paths = ["neilbot"]
